### ISSUE TITLE
Document Project Structure

### ISSUE THREAD

**Issue by svinujan** [iotwahlfach/Dokumentation#1]
- Timeline
- Members & Responsibilites
- Problem & Motivation
- Idea & Concept

**Comment by svinujan** [comment]
![Test 2](https://user-images.githubusercontent.com/51696368/59619358-a4243100-912a-11e9-9a31-b0356a9a917d.png)

**Comment by svinujan** [comment]
![Uploading Aufteilung der Bereiche.png…]()

**Comment by xmichaelw** [comment]
Fertig von @svinujan
