### ISSUE TITLE
Hackathon: Vorgehen/Organisation 

### ISSUE THREAD

**Issue by svinujan** [iotwahlfach/Dokumentation#10]

**Comment by hhzdgass** [comment]
![Organisation_Hackathon jpg](https://user-images.githubusercontent.com/51913396/59694257-9d5bf380-91e8-11e9-8cc5-e4c206ef5d6a.png)

**Comment by hhzdgass** [comment]
![P1020055](https://user-images.githubusercontent.com/51913396/59697884-eadb5f00-91ee-11e9-8710-fe21243c7c77.JPG)
