### ISSUE TITLE
Genutzte Hard- und Software 

### ISSUE THREAD

**Issue by svinujan** [iotwahlfach/Dokumentation#11]

**Comment by xmichaelw** [comment]
@hallmayer 
Zur Realisation der QR Code Reader haben wir den Raspberry Pi mit der Raspberry Pi Kamera verbunden. Desweiteren mussten zur Nutzung dieser beiden Komponenten als QR Code Reader verschiedene Technologien benutzt werden, um die Funktionalitäten eines QR Code Readers zur Verfügung zu stellen.
Als grundlegende Programmiersprache wurde für den Raspberry Pi Python benutzt. Dies lässt sich damit begründen, dass bei dem Raspberry Pi Python die standardmäßige programmiersprache darstellt, viele Libraries für den Pi auf Python aufbauen und Python wenig Overhead bei der Programmireung besitzt.
Zur Bilderkennung wurde auf das OpenCV Modul zurückgegriffen in Verbindung mit . Über diese beiden Module wird mittels eines Python Skript das Kameravideo über eine definierte Dauer auf QR Codes überprüft. Sollte ein QR Code erfasst werden wird dieser entschlüsselt und an das Backend geschickt.
Insgesamt wird die Kommunikation zwischen dem QR Code Reader und der Lichschranke der Parkbox mittels MQTT durchgeführt. Dabei werden ein MQTT Broker und der Paho MQTT Client verwendet.
Außerdem läuft auf dem Raspberry PI der MQTT Broker. Dieser wird dafür benutzt das Signal der Lichtschranke zu immitieren und eine Nachricht an den Subsciber (in unserem Fall auch der Raspberry Pi) zu schicken. Des Weiteren wird der MQTT Client über den paho mqtt Client realisiert. Dies hat den Grund, dass unser laufendes Python Skript den MQTT Channel Subscibed und sobald dieser eine Nachrcht erhält den QR Code Reader freischaltet.cmd
Die Kommunikation zwischen dem QR Code Reader und dem Backend wird weiter mittels eines REST Put requests abgewickelt. Dabei überträgt der QR Code reader die QR Code ID, die ID von sich selbst (stationId) und den Status des QR Codes.
