### ISSUE TITLE
Kapitel 3 - Prozessbeschreibung (BPMN)

### ISSUE THREAD

**Issue by svinujan** [iotwahlfach/Dokumentation#16]
- Einleitungstext und kurze Beschreibung verfassen für erstelltes Modell

**Comment by svinujan** [comment]
BPMN Prozess anpassen und BPMN-konformer machen

**Comment by hallmayer** [comment]
ABlauf passt soweit

**Comment by svinujan** [comment]
Korrektur fertig!
