### ISSUE TITLE
Kapitel 5 - Architektur 

### ISSUE THREAD

**Issue by svinujan** [iotwahlfach/Dokumentation#18]
- Architekturbeschreibung 
- Nutzung spezieller Soft- und Hardware erklären 
- Vorlesungsinhalte in Architekturbeschreibung einbinden

**Comment by hallmayer** [comment]
Kann review gelesen werden. Zumindest inhaltlich. Sprachlich bin ich selber noch nicht dazu gekommen

**Comment by hallmayer** [comment]
Werde ich aber heute abend nachholen
