### ISSUE TITLE
Kapitel 6 - Bezug zur Vorlesungsinhalten 

### ISSUE THREAD

**Issue by svinujan** [iotwahlfach/Dokumentation#19]
- Bridging the Gap 
- Ökönomisches Prinzip nach E.Fleisch
- Schlüsselelemente erwähnen, wie sie in unserem Projekt umgesetzt werden 
- Fleisch-Formel

**Comment by hhzdgass** [comment]
Sollen ich das Video einfach mit ein paar animierten Powerpoint Slides erweitern, die dann auf die Vorlesungsunterlagen bezug nehmen?
Vor allem Bridging the Gap, die Design Prinzipien und die Schlüsselelement.
Die Fleisch Formel würde ich aber eher nicht reinpacken.

**Comment by svinujan** [comment]
@hhzdgass Lass das Video so wie es ist. Nach Rücksprache mit dem Team haben wir uns entschieden, dass wir keine animierten PP-Slides in das Video einbauen.

**Comment by svinujan** [comment]
- [x] Bridging the Gap
- [x] Ökönomisches Prinzip nach E. Fleisch
- [x] Schlüsselelemente erwähnen, wie sie in unserem Projekt umgesetzt werden
- [ ] Fleisch-Formel

**Comment by xmichaelw** [comment]
hab drübergelsen und finde es soweit ganz gut, wüsste nicht was man noch hinzufügen sollte

**Comment by svinujan** [comment]
> hab drübergelsen und finde es soweit ganz gut, wüsste nicht was man noch hinzufügen sollte

Gut :)

**Comment by hallmayer** [comment]
Habs durchgelesen und ein paar Sachen ergänzt beziehungsweise angepasst. bei der fleischformel bin ich mir noch unsicher ob das so passt
