### ISSUE TITLE
Kapitel 8 - Diskussion & Ausblick 

### ISSUE THREAD

**Issue by svinujan** [iotwahlfach/Dokumentation#21]
Diskussion: 
- kritische Betrachtung des Projekt und der Entwicklung
- technische Herausforderungen 

Ausblick: 
- weitere Folgeprojekte, die aus diesem resultieren könnten 
- weitere Zusatzfunktionalitäten, die man noch einbauen könnte

**Comment by xmichaelw** [comment]
Erster Teil hinzugefügt. rest kommt noch von @JaScHhz
