### ISSUE TITLE
Discuss structure of the video

### ISSUE THREAD

**Issue by svinujan** [iotwahlfach/Dokumentation#3]
- Structure of the video 
- Voice in the video

**Comment by xmichaelw** [comment]
1.	Problemdarstellung
a.	Kunde der zum Einkaufen kommt und kein Einkaufswagen da ist
b.	Zurückbringen des Einkaufswagens und das Ding ist voll
c.	Autos die durch zu lange Schlange beim Parken gestört werden
2.	Lösungsdarstellung
a.	Abholen
i.	Person die in der Nähe vom Kaufland ist und Handy App öffnet
ii.	Closeup -> Benachrichtigung über Coupon
iii.	Abholen des Einkaufwagens
iv.	An gehen des QR Code Scanners
v.	Abscannen des Codes
vi.	Einkaufen
vii.	Bezahlen mit Code Gutschein
b.	Zurückbringen
i.	Bekommen des neuen Codes auf Kassenbon
ii.	Suche des nicht so gefüllten Einkaufwagenständers
iii.	Zurückbringen des einkaufswagens
iv.	Aktivierung des QR Code Scanners
v.	Anzeige Coupons in der App

**Comment by svinujan** [comment]
Optische Rückmeldung (LED)
