### ISSUE TITLE
Present Project Concept

### ISSUE THREAD

**Issue by svinujan** [iotwahlfach/Dokumentation#4]
- Motivation & Problem 
- Discuss/Present the Concept & Idea

**Comment by hhzdgass** [comment]
![Szenario 1](https://user-images.githubusercontent.com/51913396/59673374-79d18280-91c1-11e9-8896-9a9fef4d7e9d.png)

**Comment by hhzdgass** [comment]
[Icons.zip](https://github.com/iotwahlfach/Dokumentation/files/3301188/Icons.zip)

**Comment by hhzdgass** [comment]
![Kaufland App QR Code](https://user-images.githubusercontent.com/51913396/59678679-544a7600-91cd-11e9-829b-6a2d4aa98aac.png)

**Comment by hhzdgass** [comment]
![Kaufland App QR Code 2](https://user-images.githubusercontent.com/51913396/59679508-54e40c00-91cf-11e9-83c6-12029f516bd5.png)

**Comment by hhzdgass** [comment]
![Kassenbon 1](https://user-images.githubusercontent.com/51913396/59680431-9d042e00-91d1-11e9-87e5-974b56371643.png)
![Kassenbon 2](https://user-images.githubusercontent.com/51913396/59680432-9d042e00-91d1-11e9-8a9a-f9fdbdaa238f.png)

**Comment by svinujan** [comment]
Mit freundlichen Grüßen


Vinujan Srikanthan


________________________________
Von: hhzdgass <notifications@github.com>
Gesendet: Dienstag, 18. Juni 2019 14:01:50
An: iotwahlfach/Dokumentation
Cc: Srikanthan, Vinujan; Author
Betreff: Re: [iotwahlfach/Dokumentation] Present Project Concept (#4)


[Kassenbon 1]<https://user-images.githubusercontent.com/51913396/59680431-9d042e00-91d1-11e9-87e5-974b56371643.png>
[Kassenbon 2]<https://user-images.githubusercontent.com/51913396/59680432-9d042e00-91d1-11e9-8a9a-f9fdbdaa238f.png>

-

**Comment by hhzdgass** [comment]
![Entnahme](https://user-images.githubusercontent.com/51913396/59681904-50baed00-91d5-11e9-8266-dcbf57e47616.png)
![Rückgabe](https://user-images.githubusercontent.com/51913396/59681905-50baed00-91d5-11e9-8257-6fe5444f0b04.png)
