### ISSUE TITLE
Modellierung in BPMN 

### ISSUE THREAD

**Issue by svinujan** [iotwahlfach/Dokumentation#7]

**Comment by hhzdgass** [comment]
![BPMN IoT Entnahme Prozess](https://user-images.githubusercontent.com/51913396/59694426-e744d980-91e8-11e9-898a-1cb83bb8b606.png)
![BPMN IoT Rückgabeprozess](https://user-images.githubusercontent.com/51913396/59694439-e9a73380-91e8-11e9-9b59-cdca39332b82.png)

**Comment by hhzdgass** [comment]
![BPMN IoT Entnahme Prozess](https://user-images.githubusercontent.com/51913396/59698055-30982780-91ef-11e9-9222-a06ea1826630.png)
![BPMN IoT Rückgabeprozess](https://user-images.githubusercontent.com/51913396/59698056-30982780-91ef-11e9-8e00-937dfc26b675.png)
